### ISSUE TITLE
when no stock news were found, it crashed.

### ISSUE THREAD

**Issue by doncat99** [anfederico/Stockeye#2]
This run will take approximately 9.0 minutes
url https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20yahoo.finance.quotes%20where%20symbol%20in%20(%22MSFT%22%2C%22PFE%22%2C%22BOX%22%2C%22MNST%22%2C%22LLY%22%2C%22AAPL%22%2C%22BBY%22%2C%22TSLA%22%2C%22WFG%22%2C%22AMZN%22%2C%22JNJ%22%2C%22NFLX%22%2C%22BIIB%22%2C%22GE%22%2C%22GILD%22%2C%22SHAK%22%2C%22VRTX%22%2C%22CMG%22)%0A%09%09&format=json&diagnostics=true&env=http%3A%2F%2Fdatatables.org%2Falltables.env&callback=
No Stocks Found!
stats None
Traceback (most recent call last):
  File "test-news.py", line 40, in <module>
    watch(credentials, ticks, properties, threshold, hourspast, sentences, firstlast)
  File "watch.py", line 326, in watch
    for symbol in stats:
TypeError: 'NoneType' object is not iterable

**Comment by kncshw** [comment]
Same issue here

**Comment by marios-keri** [comment]
It's a query error, it returns a json error 

 /**/yql_invalid_callback({"error":{"lang":"en-US","diagnostics":null,"description":"Invalid JSON callback parameter yql_invalid_callback"}});

Because the 'stats' variable got a json error it produce a " TypeError: 'NoneType' object is not iterable.

the parameters are wrong.
